server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/issuewatch_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:MySQL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size:5MB
spring.servlet.multipart.max-request-size=20MB

app.upload.dir=${APP_UPLOAD_DIR:uploads}

app.jwt.secrete=${JWT_SECRETE:r5ut65zS3dWIUt1LK7UBzVdbwW150Bsk}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}

app.mail.from=${MAIL_FROM:no-reply@issuewatch.local}

jobs.enabled=${JOBS_ENABLED:true}
